import json
import pandas as pd
from pathlib import Path
import argparse

def compile_metrics(results_dir="results", output_filename_base="compiled_training_metrics"):
    results_path = Path(results_dir)
    all_metrics = []

    print(f"Scanning {results_path} for metrics.json files...")

    # Recursively find all metrics.json files
    for metrics_file in results_path.rglob("metrics.json"):
        try:
            with open(metrics_file, 'r') as f:
                data = json.load(f)

            # 1. Extract basic model identifiers
            model_name = data.get("model_name", "UNKNOWN")
            
            # 2. Parse Architecture and Rank (Fixed to support non-LoRA baselines)
            if "_R" in model_name:
                parts = model_name.rsplit("_R", 1)
                arch = parts[0]
                rank = parts[1]
            elif "_FULL" in model_name:
                arch = model_name.replace("_FULL", "")
                rank = "0"
            else:
                arch = model_name
                rank = "0"

            # 3. Extract parameter efficiency data
            params = data.get("parameters", {})
            
            # 4. Extract the best validation metrics
            # Matches the "val_best" structure generated by trainer_seg.py
            seg_metrics = data.get("seg_metrics", {}).get("val_best", {})
            
            # 5. Flatten the data into a single dictionary row
            row = {
                "Architecture": arch,
                "Rank": rank,
                "Trainable %": params.get("trainable_percentage"),
                "Trainable Params": params.get("trainable_parameters"),
                "Total Params": params.get("total_parameters")
            }
            
            # Merge all segmentation and phase volume metrics into the row
            row.update(seg_metrics)
            all_metrics.append(row)
            
            print(f"  -> Extracted: {model_name}")
            
        except Exception as e:
            print(f"[Warning] Could not parse {metrics_file}: {e}")

    # 6. Convert to Pandas DataFrame, sort, and save
    if all_metrics:
        df = pd.DataFrame(all_metrics)
        
        # Sort logically by Architecture, then mathematically by Rank (0, 2, 4, 8, 16, 32)
        df['Rank_Num'] = pd.to_numeric(df['Rank'], errors='coerce')
        df = df.sort_values(by=['Architecture', 'Rank_Num']).drop(columns=['Rank_Num'])
        
        # Reorder columns to put the most important headline metrics first
        cols = df.columns.tolist()
        headline_cols = [
            "Architecture", "Rank", "Trainable %", 
            "mean_dice", "mean_iou", "aji", "bf1", "phase_vol_error"
        ]
        
        # Organize: Headline metrics first, then the remaining per-class metrics
        ordered_cols = [c for c in headline_cols if c in cols] + \
                       [c for c in cols if c not in headline_cols]
        df = df[ordered_cols]
        
        # Export to CSV
        csv_path = results_path / f"{output_filename_base}.csv"
        df.to_csv(csv_path, index=False)
        
        # Export to JSON
        json_path = results_path / f"{output_filename_base}.json"
        df.to_json(json_path, orient="records", indent=4)
        
        print(f"\n[SUCCESS] Compiled {len(all_metrics)} models.")
        print(f"  -> Saved CSV : {csv_path}")
        print(f"  -> Saved JSON: {json_path}")
        
    else:
        print("\n[NOTICE] No metrics.json files found. Have you completed a training run?")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compile all LoRA rank sweep metrics into CSV and JSON.")
    parser.add_argument("--results_dir", default="results", help="Directory containing the training results.")
    parser.add_argument("--output_base", default="compiled_training_metrics", help="Base filename for outputs (without extension).")
    args = parser.parse_args()
    
    compile_metrics(args.results_dir, args.output_base)